{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "craftique-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "craftique-frontend.labels" . | nindent 4 }}
  annotations:
    craftique.io/description: "Network policy for frontend pod communication"
spec:
  podSelector:
    matchLabels:
      {{- include "craftique-frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
