{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "craftique-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "craftique-frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "craftique-frontend.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
{{- end }}
