apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-platform
    craftique.io/public-facing: "false"
  annotations:
    craftique.io/description: "PostgreSQL database service endpoint"
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None # Headless service for StatefulSet