apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    encryption: enabled
    environment: production
    owner: secdevops-team
    project: craftique-482022
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # standard-rwo provides encryption at rest by default (Google-managed keys)
  storageClassName: standard-rwo