apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: craftique
    app.kubernetes.io/managed-by: argocd
    environment: production
    owner: secdevops-team
    project: phd-craftique
    cost-center: education
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: craftique
        environment: production
        owner: secdevops-team
    spec:
      # Pod-level security context - ensure postgres user (70) can access volumes
      securityContext:
        fsGroup: 70
        runAsUser: 70
        runAsGroup: 70
      containers:
        - name: postgres
          image: postgres:15-alpine
          # Container-level security context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            # TODO: Engineer 4 will replace this with ExternalSecret reference later
            - name: POSTGRES_PASSWORD
              value: "craftique_temp_password" 
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app: postgres
          app.kubernetes.io/name: postgres
          app.kubernetes.io/component: database
          encryption: enabled
      spec:
        accessModes: [ "ReadWriteOnce" ]
        # standard-rwo provides encryption at rest by default (Google-managed keys)
        storageClassName: "standard-rwo"
        resources:
          requests:
            storage: 10Gi