apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  # VIOLATION: Removing mandatory asset tagging/governance labels
  # Missing: craftique.io/owner, craftique.io/environment, craftique.io/cost-center
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  # VIOLATION: Changing ClusterIP: None to LoadBalancer 
  # This exposes a private database to the public internet, violating "Least-Privilege" design
  type: LoadBalancer