# PostgreSQL Credentials ExternalSecret
# This syncs secrets from GCP Secret Manager into a Kubernetes Secret
# The External Secrets Operator will automatically create a Secret named 'postgres-credentials'
#
# Prerequisites:
# 1. Create secrets in GCP Secret Manager with these names:
#    - craftique-postgres-password
#    - craftique-postgres-user  
#    - craftique-postgres-db
# 2. Ensure the SecretStore is configured (gcp-secretstore.yaml)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: default
spec:
  # Refresh interval - how often to check for updates in GCP
  refreshInterval: 1h
  
  # Reference to the SecretStore
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  
  # Target Kubernetes Secret to create
  target:
    name: postgres-credentials
    creationPolicy: Owner
  
  # Data to sync from GCP Secret Manager
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: craftique-postgres-password  # Name of secret in GCP Secret Manager
  
  - secretKey: POSTGRES_USER
    remoteRef:
      key: craftique-postgres-user
  
  - secretKey: POSTGRES_DB
    remoteRef:
      key: craftique-postgres-db
