apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftique-frontend
  namespace: default
  labels:
    app: craftique-frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: craftique
    app.kubernetes.io/managed-by: argocd
    environment: production
    owner: secdevops-team
    project: phd-craftique
    cost-center: education
spec:
  replicas: 2
  selector:
    matchLabels:
      app: craftique-frontend
  template:
    metadata:
      labels:
        app: craftique-frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: craftique
        environment: production
        owner: secdevops-team
    spec:
      # Image pull secret for GCP Artifact Registry authentication
      # Create with: kubectl create secret docker-registry gcr-json-key \
      #   --docker-server=us-central1-docker.pkg.dev \
      #   --docker-username=_json_key \
      #   --docker-password="$(cat key.json)" \
      #   --docker-email=user@example.com
      imagePullSecrets:
        - name: gcp-pull-secret

      securityContext:
        runAsUser: 1001
      containers:
        - name: frontend
          # GCP Artifact Registry image path
          # Format: REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE:TAG
          # Update ARTIFACT_REPO_NAME with your actual repository name from GCP
          image: europe-west10-docker.pkg.dev/craftique-482022/craftique-registry/frontend:latest
          imagePullPolicy: Always
          # Container-level security context
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nextjs-cache
              mountPath: /app/.next/cache
          ports:
            - containerPort: 3000
          env:
            # API_BASE_URL is used for server-side rendering (SSR) - internal cluster communication
            - name: API_BASE_URL
              value: "http://backend-service:8000/api/v1"
            # NEXT_PUBLIC_API_BASE_URL is used for client-side - external domain
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://craftique.chickenkiller.com/api/v1"
            - name: APP_BASE_URL
              value: "https://craftique.chickenkiller.com"
            # Auth0 credentials from Secret
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_DOMAIN
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_CLIENT_SECRET
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_SECRET
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_AUDIENCE
            - name: AUTH0_ISSUER
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_ISSUER
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nextjs-cache
          emptyDir: {}
