apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftique-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: craftique-frontend
  template:
    metadata:
      labels:
        app: craftique-frontend
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: frontend
          # TODO: Update with real image
          image: craftique-frontend:latest
          # Container-level security context
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nextjs-cache
              mountPath: /app/.next/cache
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://craftique.chickenkiller.com/api/v1"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nextjs-cache
          emptyDir: {}