# Kyverno ClusterPolicy: Require Image Digests
# This policy blocks deployments using mutable tags like :latest
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-image-digests
  annotations:
    policies.kyverno.io/title: Require Image Digests
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Requires all container images to use immutable digests (@sha256:...)
      instead of mutable tags like :latest. This ensures deployments are
      reproducible and prevents supply chain attacks via tag manipulation.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-digest-for-craftique-images
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - default
                - production
                - staging
      validate:
        message: >-
          Container images must use digests (@sha256:...) instead of tags.
          Image '{{ element.image }}' uses a mutable tag. 
          Use the signed image digest from CI/CD pipeline instead.
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                all:
                  # Check if image is from GCP Artifact Registry
                  - key: "{{ element.image }}"
                    operator: AnyIn
                    value:
                      - "*-docker.pkg.dev/*"
                  # Deny if not using digest
                  - key: "{{ element.image }}"
                    operator: AnyNotIn
                    value:
                      - "*@sha256:*"
          - list: "request.object.spec.initContainers || []"
            deny:
              conditions:
                all:
                  - key: "{{ element.image }}"
                    operator: AnyIn
                    value:
                      - "*-docker.pkg.dev/*"
                  - key: "{{ element.image }}"
                    operator: AnyNotIn
                    value:
                      - "*@sha256:*"

    - name: block-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - default
                - production
                - staging
      validate:
        message: "The ':latest' tag is not allowed. Use a specific version or digest."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.image }}"
                    operator: Equals
                    value: "*:latest"
          - list: "request.object.spec.initContainers || []"
            deny:
              conditions:
                any:
                  - key: "{{ element.image }}"
                    operator: Equals
                    value: "*:latest"
