# Kyverno Policy - Enforce Asset Tagging Standards
# Validates that all resources have required governance labels
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
  annotations:
    policies.kyverno.io/title: Require Standard Labels
    policies.kyverno.io/category: Asset Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Deployment, StatefulSet, Service
    policies.kyverno.io/description: >-
      Enforces standard Kubernetes labels and governance labels on all workloads.
      Required for cost tracking, ownership mapping, and compliance auditing.
      Aligns with Kubernetes Recommended Labels and FinOps best practices.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    # Rule 1: Require standard Kubernetes labels
    - name: require-app-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Service
      validate:
        message: >-
          Resources must include standard Kubernetes labels:
          app.kubernetes.io/name, app.kubernetes.io/component, app.kubernetes.io/part-of.
          See: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: "?*"
              app.kubernetes.io/component: "?*"
              app.kubernetes.io/part-of: "?*"
    
    # Rule 2: Require governance labels
    - name: require-governance-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      validate:
        message: >-
          Workloads must include governance labels for cost tracking and ownership:
          craftique.io/owner, craftique.io/environment, craftique.io/cost-center.
          These enable cost allocation, accountability, and compliance auditing.
        pattern:
          metadata:
            labels:
              craftique.io/owner: "?*"
              craftique.io/environment: "?*"
              craftique.io/cost-center: "?*"
    
    # Rule 3: Validate environment label values
    - name: validate-environment-values
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Service
                - ConfigMap
                - Secret
      validate:
        message: >-
          craftique.io/environment must be one of: production, staging, development.
          Use consistent values for accurate cost allocation and environment segmentation.
        pattern:
          metadata:
            =(labels):
              =(craftique.io/environment): "production | staging | development"
    
    # Rule 4: Validate owner label values
    - name: validate-owner-values
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      validate:
        message: >-
          craftique.io/owner must be a valid team:
          platform-team, backend-team, frontend-team, devops-team, data-team.
          Contact platform-team to add new owner values.
        pattern:
          metadata:
            labels:
              craftique.io/owner: "platform-team | backend-team | frontend-team | devops-team | data-team"
    
    # Rule 5: Validate cost-center label values
    - name: validate-cost-center-values
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - PersistentVolumeClaim
      validate:
        message: >-
          craftique.io/cost-center must be a valid cost center:
          eng-platform, eng-backend, eng-frontend, product-alpha, shared-services.
          Contact finance to add new cost centers.
        pattern:
          metadata:
            labels:
              craftique.io/cost-center: "eng-platform | eng-backend | eng-frontend | product-alpha | shared-services"
    
    # Rule 6: Require data classification for databases and secrets
    - name: require-data-classification
      match:
        any:
          - resources:
              kinds:
                - StatefulSet
              selector:
                matchLabels:
                  app.kubernetes.io/component: database
          - resources:
              kinds:
                - Secret
      validate:
        message: >-
          Databases and Secrets must specify data classification:
          craftique.io/data-classification (public, internal, confidential, restricted).
          This is required for compliance with data protection regulations.
        pattern:
          metadata:
            labels:
              craftique.io/data-classification: "public | internal | confidential | restricted"
    
    # Rule 7: Require backup-policy for StatefulSets
    - name: require-backup-policy
      match:
        any:
          - resources:
              kinds:
                - StatefulSet
      validate:
        message: >-
          StatefulSets must specify backup policy:
          craftique.io/backup-policy (daily, weekly, monthly, never).
          This ensures data protection and disaster recovery readiness.
        pattern:
          metadata:
            labels:
              craftique.io/backup-policy: "daily | weekly | monthly | never"
    
    # Rule 8: Require monitoring label for workloads
    - name: require-monitoring-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      validate:
        message: >-
          Workloads must specify monitoring status:
          craftique.io/monitoring (enabled, disabled).
          This controls Prometheus scraping and alerting.
        pattern:
          metadata:
            labels:
              craftique.io/monitoring: "enabled | disabled"
    
    # Rule 9: Propagate labels to Pod templates
    - name: propagate-labels-to-pods
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      validate:
        message: >-
          Pod template labels must include app.kubernetes.io/name, app.kubernetes.io/component,
          and governance labels for proper service mesh and monitoring integration.
        pattern:
          spec:
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: "?*"
                  app.kubernetes.io/component: "?*"
                  craftique.io/owner: "?*"
                  craftique.io/environment: "?*"
---
# Kyverno Policy - Mutate Missing Labels (Auto-remediation)
# Automatically adds missing labels based on namespace or defaults
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-labels
  annotations:
    policies.kyverno.io/title: Add Default Labels
    policies.kyverno.io/category: Asset Management
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod, Deployment, StatefulSet
    policies.kyverno.io/description: >-
      Automatically adds default governance labels to resources if not specified.
      Reduces manual effort and ensures consistent labeling across the platform.
spec:
  background: true
  rules:
    # Rule 1: Add default part-of label
    - name: add-part-of-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - Service
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(app.kubernetes.io/part-of): craftique-ecommerce
    
    # Rule 2: Add managed-by label for ArgoCD-managed resources
    - name: add-managed-by-argocd
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - Service
              namespaces:
                - default
                - production
                - staging
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(app.kubernetes.io/managed-by): argocd
    
    # Rule 3: Add monitoring=enabled for production workloads
    - name: add-monitoring-enabled
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
              selector:
                matchLabels:
                  craftique.io/environment: production
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(craftique.io/monitoring): enabled
    
    # Rule 4: Propagate namespace labels to resources
    - name: propagate-namespace-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - Service
      context:
        - name: namespaceLabels
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.namespace}}"
            jmesPath: "metadata.labels"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(craftique.io/environment): "{{ namespaceLabels.\"craftique.io/environment\" || 'development' }}"
---
# Kyverno Policy - Generate Label Reports
# Creates PolicyReports for resources missing recommended labels
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-recommended-labels
  annotations:
    policies.kyverno.io/title: Audit Recommended Labels
    policies.kyverno.io/category: Asset Management
    policies.kyverno.io/severity: low
    policies.kyverno.io/description: >-
      Audits resources for recommended but not required labels.
      Generates warnings in PolicyReports for visibility.
spec:
  validationFailureAction: Audit  # Warn only, don't block
  background: true
  rules:
    # Rule 1: Recommend version label
    - name: recommend-version-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      validate:
        message: >-
          Recommended: Add app.kubernetes.io/version label for version tracking.
          Example: app.kubernetes.io/version: "1.2.3"
        pattern:
          metadata:
            labels:
              app.kubernetes.io/version: "?*"
    
    # Rule 2: Recommend criticality label
    - name: recommend-criticality-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      validate:
        message: >-
          Recommended: Add craftique.io/criticality label for SLA tracking.
          Values: critical, high, medium, low
        pattern:
          metadata:
            labels:
              craftique.io/criticality: "?*"
    
    # Rule 3: Recommend public-facing label
    - name: recommend-public-facing-label
      match:
        any:
          - resources:
              kinds:
                - Service
              selector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - LoadBalancer
                      - NodePort
      validate:
        message: >-
          Recommended: Add craftique.io/public-facing label for security posture tracking.
          Values: "true" or "false"
        pattern:
          metadata:
            labels:
              craftique.io/public-facing: "?*"
    
    # Rule 4: Recommend description annotation
    - name: recommend-description-annotation
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - Service
      validate:
        message: >-
          Recommended: Add craftique.io/description annotation for human-readable documentation.
          Example: "Backend REST API service for Craftique e-commerce platform"
        pattern:
          metadata:
            annotations:
              craftique.io/description: "?*"
