# PodDisruptionBudget for Backend
# Ensures high availability during voluntary disruptions (updates, drains)
#
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: craftique-backend-pdb
  namespace: default
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-backend
  annotations:
    craftique.io/description: "PodDisruptionBudget ensuring minimum backend availability during disruptions"
spec:
  minAvailable: 1  # At least 1 pod must be available during disruptions
  selector:
    matchLabels:
      app: craftique-backend
  unhealthyPodEvictionPolicy: IfHealthyBudget  # Only evict if budget allows
---
# PodDisruptionBudget for Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: craftique-frontend-pdb
  namespace: default
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-frontend
  annotations:
    craftique.io/description: "PodDisruptionBudget ensuring minimum frontend availability during disruptions"
spec:
  minAvailable: 1  # At least 1 pod must be available during disruptions
  selector:
    matchLabels:
      app: craftique-frontend
  unhealthyPodEvictionPolicy: IfHealthyBudget
---
# PodDisruptionBudget for PostgreSQL
# More strict for database - ensures data safety
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-platform
  annotations:
    craftique.io/description: "PodDisruptionBudget ensuring database availability during disruptions"
spec:
  minAvailable: 1  # Database must stay available
  selector:
    matchLabels:
      app: postgres
  unhealthyPodEvictionPolicy: AlwaysAllow  # Allow eviction of unhealthy pods
---
# PodDisruptionBudget for Production Backend (higher availability)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: craftique-backend-pdb-production
  namespace: production
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: backend
    app.kubernetes.io/environment: production
spec:
  minAvailable: 2  # Production requires 2 pods minimum
  selector:
    matchLabels:
      app: craftique-backend
  unhealthyPodEvictionPolicy: IfHealthyBudget
---
# PodDisruptionBudget for Production Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: craftique-frontend-pdb-production
  namespace: production
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: frontend
    app.kubernetes.io/environment: production
spec:
  minAvailable: 2  # Production requires 2 pods minimum
  selector:
    matchLabels:
      app: craftique-frontend
  unhealthyPodEvictionPolicy: IfHealthyBudget
