# ResourceQuota - Limits resources in the default namespace
# Prevents resource exhaustion and ensures fair resource allocation
#
apiVersion: v1
kind: ResourceQuota
metadata:
  name: craftique-resource-quota
  namespace: default
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: governance
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-platform
  annotations:
    craftique.io/description: "Resource quota for default namespace to prevent resource exhaustion"
spec:
  hard:
    # Compute Resources
    requests.cpu: "4"           # Total CPU requests across all pods
    requests.memory: "8Gi"      # Total memory requests across all pods
    limits.cpu: "8"             # Total CPU limits across all pods
    limits.memory: "16Gi"       # Total memory limits across all pods
    
    # Storage
    requests.storage: "100Gi"   # Total storage requests
    persistentvolumeclaims: "10" # Max number of PVCs
    
    # Object Counts
    pods: "20"                  # Maximum number of pods
    services: "10"              # Maximum number of services
    configmaps: "20"            # Maximum number of ConfigMaps
    secrets: "30"               # Maximum number of Secrets
    replicationcontrollers: "10"
    
    # Services (LoadBalancers)
    services.loadbalancers: "2" # Limit expensive LoadBalancers
    services.nodeports: "5"     # Limit NodePort services
---
# ResourceQuota for Production namespace (if used)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: craftique-resource-quota-production
  namespace: production
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: governance
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/environment: production
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-platform
  annotations:
    craftique.io/description: "Resource quota for production namespace with higher limits"
spec:
  hard:
    # Production gets more resources
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    requests.storage: "500Gi"
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    configmaps: "50"
    secrets: "50"
    services.loadbalancers: "3"
    services.nodeports: "5"
---
# ResourceQuota for Staging namespace (if used)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: craftique-resource-quota-staging
  namespace: staging
  labels:
    app.kubernetes.io/name: craftique
    app.kubernetes.io/component: governance
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/environment: staging
    craftique.io/owner: platform-team
    craftique.io/environment: staging
    craftique.io/cost-center: eng-platform
    craftique.io/auto-shutdown: enabled
  annotations:
    craftique.io/description: "Resource quota for staging namespace with moderate limits"
spec:
  hard:
    # Staging gets moderate resources
    requests.cpu: "6"
    requests.memory: "12Gi"
    limits.cpu: "12"
    limits.memory: "24Gi"
    requests.storage: "200Gi"
    persistentvolumeclaims: "15"
    pods: "30"
    services: "15"
    configmaps: "30"
    secrets: "40"
    services.loadbalancers: "2"
    services.nodeports: "5"
