apiVersion: v1
kind: ResourceQuota
metadata:
  name: craftique-quota
  namespace: default
  labels:
    app.kubernetes.io/name: resource-quota
    app.kubernetes.io/component: governance
    app.kubernetes.io/part-of: craftique
    app.kubernetes.io/managed-by: argocd
    environment: production
    owner: secdevops-team
    project: phd-craftique
    cost-center: education
spec:
  hard:
    # Limit total resources in namespace
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    
    # Limit number of objects
    pods: "10"
    services: "5"
    configmaps: "10"
    persistentvolumeclaims: "3"
    secrets: "10"
