# ClusterSecretStore - Connects to GCP Secret Manager
# This defines a cluster-wide secret store that ExternalSecrets can reference
# Supports: GCP Secret Manager, AWS Secrets Manager, Azure Key Vault, HashiCorp Vault
#
# Prerequisites:
# 1. Install External Secrets Operator: 
#    helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace
# 2. Create GCP Service Account with Secret Manager Secret Accessor role
# 3. Store SA key as K8s secret: kubectl create secret generic gcp-sm-sa --from-file=secret-access-credentials=./sa-key.json -n external-secrets
#
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: craftique-ecommerce
    app.kubernetes.io/managed-by: kubectl
    craftique.io/owner: platform-team
    craftique.io/environment: production
    craftique.io/cost-center: eng-platform
    craftique.io/data-classification: restricted
  annotations:
    craftique.io/description: "Cluster-wide secret store connecting to GCP Secret Manager"
spec:
  provider:
    gcpsm:
      # GCP Project ID where secrets are stored
      projectID: craftique-project  # TODO: Replace with actual GCP project ID
      auth:
        secretRef:
          secretAccessKeySecretRef:
            # Reference to the GCP Service Account key stored as K8s secret
            name: gcp-sm-sa
            key: secret-access-credentials
            namespace: external-secrets
---
# Alternative: Fake provider for local development/testing
# Uncomment this and comment out the GCP provider above for local testing
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: fake-secret-store
# spec:
#   provider:
#     fake:
#       data:
#         - key: "/craftique/database/password"
#           value: "super-secure-db-password-from-vault"
#         - key: "/craftique/database/username"
#           value: "craftique"
#         - key: "/craftique/jwt/secret"
#           value: "jwt-secret-from-vault-32-chars-min"
#         - key: "/craftique/cookie/secret"
#           value: "cookie-secret-from-vault-32chars"
