# GCP Secret Manager SecretStore
# This connects External Secrets Operator to GCP Secret Manager
#
# Prerequisites:
# 1. GCP service account with Secret Manager Secret Accessor role
# 2. Service account key stored as Kubernetes secret
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: default
spec:
  provider:
    gcpsm:
      # Your GCP project ID
      projectID: "YOUR_GCP_PROJECT_ID"  # Replace with your actual project ID
      
      # Authentication using Workload Identity (recommended) or service account key
      # Option 1: Workload Identity (recommended for GKE)
      # auth:
      #   workloadIdentity:
      #     clusterLocation: us-central1
      #     clusterName: your-cluster-name
      #     serviceAccountRef:
      #       name: external-secrets
      
      # Option 2: Service Account Key (works on any cluster)
      auth:
        secretRef:
          secretAccessKey:
            name: gcp-secret-manager-key
            key: key.json
            namespace: external-secrets
