apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftique-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Craft-Cart/craftique-gitops-manifests.git
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
