apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: craftique
    app.kubernetes.io/managed-by: argocd
    environment: production
    owner: secdevops-team
    project: craftique-482022
    cost-center: education
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: omar.samir.galal@gmail.com
    profile: tlsserver
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
